/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConceptRouteImport } from './routes/concept'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OfficeRouteImport } from './routes/office'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiRtcRouteImport } from './routes/api/rtc'
import { Route as ConsultIdRouteImport } from './routes/consult.$id'
import { Route as OfficeIndexRouteImport } from './routes/office/index'
import { Route as OfficeAppointmentsRouteImport } from './routes/office/appointments'
import { Route as OfficeClientsRouteImport } from './routes/office/clients'
import { Route as OfficeDocumentsRouteImport } from './routes/office/documents'
import { Route as OfficeLaunchRouteImport } from './routes/office/launch'
import { Route as OfficeMessagesRouteImport } from './routes/office/messages'
import { Route as OfficeOffersRouteImport } from './routes/office/offers'
import { Route as OfficeReportsRouteImport } from './routes/office/reports'
import { Route as OfficeRequestsRouteImport } from './routes/office/requests'
import { Route as OfficeSettingsRouteImport } from './routes/office/settings'
import { Route as OfficeTasksRouteImport } from './routes/office/tasks'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as PortalAccountRouteImport } from './routes/portal/account'
import { Route as PortalAppointmentsRouteImport } from './routes/portal/appointments'
import { Route as PortalRequestsRouteImport } from './routes/portal/requests'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as OfficeClientsIndexRouteImport } from './routes/office/clients/index'
import { Route as OfficeClientsClientIdRouteImport } from './routes/office/clients/$clientId'
import { Route as PortalServicesSlugRouteImport } from './routes/portal/services.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptRoute = ConceptRouteImport.update({
  id: '/concept',
  path: '/concept',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeRoute = OfficeRouteImport.update({
  id: '/office',
  path: '/office',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRtcRoute = ApiRtcRouteImport.update({
  id: '/api/rtc',
  path: '/api/rtc',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultIdRoute = ConsultIdRouteImport.update({
  id: '/consult/$id',
  path: '/consult/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeIndexRoute = OfficeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficeAppointmentsRoute = OfficeAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficeClientsRoute = OfficeClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficeDocumentsRoute = OfficeDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficeLaunchRoute = OfficeLaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficeMessagesRoute = OfficeMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficeOffersRoute = OfficeOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficeReportsRoute = OfficeReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficeRequestsRoute = OfficeRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficeSettingsRoute = OfficeSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficeTasksRoute = OfficeTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => OfficeRoute,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAccountRoute = PortalAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAppointmentsRoute = PortalAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => PortalRoute,
} as any)
const PortalRequestsRoute = PortalRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => PortalRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeClientsIndexRoute = OfficeClientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OfficeClientsRoute,
} as any)
const OfficeClientsClientIdRoute = OfficeClientsClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => OfficeClientsRoute,
} as any)
const PortalServicesSlugRoute = PortalServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => PortalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/concept': typeof ConceptRoute
  '/login': typeof LoginRoute
  '/office': typeof OfficeRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/terms': typeof TermsRoute
  '/api/rtc': typeof ApiRtcRoute
  '/consult/$id': typeof ConsultIdRoute
  '/office/appointments': typeof OfficeAppointmentsRoute
  '/office/clients': typeof OfficeClientsRouteWithChildren
  '/office/documents': typeof OfficeDocumentsRoute
  '/office/launch': typeof OfficeLaunchRoute
  '/office/messages': typeof OfficeMessagesRoute
  '/office/offers': typeof OfficeOffersRoute
  '/office/reports': typeof OfficeReportsRoute
  '/office/requests': typeof OfficeRequestsRoute
  '/office/settings': typeof OfficeSettingsRoute
  '/office/tasks': typeof OfficeTasksRoute
  '/portal/account': typeof PortalAccountRoute
  '/portal/appointments': typeof PortalAppointmentsRoute
  '/portal/requests': typeof PortalRequestsRoute
  '/office/': typeof OfficeIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/office/clients/$clientId': typeof OfficeClientsClientIdRoute
  '/portal/services/$slug': typeof PortalServicesSlugRoute
  '/office/clients/': typeof OfficeClientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/concept': typeof ConceptRoute
  '/login': typeof LoginRoute
  '/terms': typeof TermsRoute
  '/api/rtc': typeof ApiRtcRoute
  '/consult/$id': typeof ConsultIdRoute
  '/office/appointments': typeof OfficeAppointmentsRoute
  '/office/documents': typeof OfficeDocumentsRoute
  '/office/launch': typeof OfficeLaunchRoute
  '/office/messages': typeof OfficeMessagesRoute
  '/office/offers': typeof OfficeOffersRoute
  '/office/reports': typeof OfficeReportsRoute
  '/office/requests': typeof OfficeRequestsRoute
  '/office/settings': typeof OfficeSettingsRoute
  '/office/tasks': typeof OfficeTasksRoute
  '/portal/account': typeof PortalAccountRoute
  '/portal/appointments': typeof PortalAppointmentsRoute
  '/portal/requests': typeof PortalRequestsRoute
  '/office': typeof OfficeIndexRoute
  '/portal': typeof PortalIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/office/clients/$clientId': typeof OfficeClientsClientIdRoute
  '/portal/services/$slug': typeof PortalServicesSlugRoute
  '/office/clients': typeof OfficeClientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/concept': typeof ConceptRoute
  '/login': typeof LoginRoute
  '/office': typeof OfficeRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/terms': typeof TermsRoute
  '/api/rtc': typeof ApiRtcRoute
  '/consult/$id': typeof ConsultIdRoute
  '/office/appointments': typeof OfficeAppointmentsRoute
  '/office/clients': typeof OfficeClientsRouteWithChildren
  '/office/documents': typeof OfficeDocumentsRoute
  '/office/launch': typeof OfficeLaunchRoute
  '/office/messages': typeof OfficeMessagesRoute
  '/office/offers': typeof OfficeOffersRoute
  '/office/reports': typeof OfficeReportsRoute
  '/office/requests': typeof OfficeRequestsRoute
  '/office/settings': typeof OfficeSettingsRoute
  '/office/tasks': typeof OfficeTasksRoute
  '/portal/account': typeof PortalAccountRoute
  '/portal/appointments': typeof PortalAppointmentsRoute
  '/portal/requests': typeof PortalRequestsRoute
  '/office/': typeof OfficeIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/office/clients/$clientId': typeof OfficeClientsClientIdRoute
  '/portal/services/$slug': typeof PortalServicesSlugRoute
  '/office/clients/': typeof OfficeClientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/concept'
    | '/login'
    | '/office'
    | '/portal'
    | '/terms'
    | '/api/rtc'
    | '/consult/$id'
    | '/office/appointments'
    | '/office/clients'
    | '/office/documents'
    | '/office/launch'
    | '/office/messages'
    | '/office/offers'
    | '/office/reports'
    | '/office/requests'
    | '/office/settings'
    | '/office/tasks'
    | '/portal/account'
    | '/portal/appointments'
    | '/portal/requests'
    | '/office/'
    | '/portal/'
    | '/api/auth/$'
    | '/office/clients/$clientId'
    | '/portal/services/$slug'
    | '/office/clients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/concept'
    | '/login'
    | '/terms'
    | '/api/rtc'
    | '/consult/$id'
    | '/office/appointments'
    | '/office/documents'
    | '/office/launch'
    | '/office/messages'
    | '/office/offers'
    | '/office/reports'
    | '/office/requests'
    | '/office/settings'
    | '/office/tasks'
    | '/portal/account'
    | '/portal/appointments'
    | '/portal/requests'
    | '/office'
    | '/portal'
    | '/api/auth/$'
    | '/office/clients/$clientId'
    | '/portal/services/$slug'
    | '/office/clients'
  id:
    | '__root__'
    | '/'
    | '/concept'
    | '/login'
    | '/office'
    | '/portal'
    | '/terms'
    | '/api/rtc'
    | '/consult/$id'
    | '/office/appointments'
    | '/office/clients'
    | '/office/documents'
    | '/office/launch'
    | '/office/messages'
    | '/office/offers'
    | '/office/reports'
    | '/office/requests'
    | '/office/settings'
    | '/office/tasks'
    | '/portal/account'
    | '/portal/appointments'
    | '/portal/requests'
    | '/office/'
    | '/portal/'
    | '/api/auth/$'
    | '/office/clients/$clientId'
    | '/portal/services/$slug'
    | '/office/clients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConceptRoute: typeof ConceptRoute
  LoginRoute: typeof LoginRoute
  OfficeRoute: typeof OfficeRouteWithChildren
  PortalRoute: typeof PortalRouteWithChildren
  TermsRoute: typeof TermsRoute
  ApiRtcRoute: typeof ApiRtcRoute
  ConsultIdRoute: typeof ConsultIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concept': {
      id: '/concept'
      path: '/concept'
      fullPath: '/concept'
      preLoaderRoute: typeof ConceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office': {
      id: '/office'
      path: '/office'
      fullPath: '/office'
      preLoaderRoute: typeof OfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rtc': {
      id: '/api/rtc'
      path: '/api/rtc'
      fullPath: '/api/rtc'
      preLoaderRoute: typeof ApiRtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consult/$id': {
      id: '/consult/$id'
      path: '/consult/$id'
      fullPath: '/consult/$id'
      preLoaderRoute: typeof ConsultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office/': {
      id: '/office/'
      path: '/'
      fullPath: '/office/'
      preLoaderRoute: typeof OfficeIndexRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/appointments': {
      id: '/office/appointments'
      path: '/appointments'
      fullPath: '/office/appointments'
      preLoaderRoute: typeof OfficeAppointmentsRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/clients': {
      id: '/office/clients'
      path: '/clients'
      fullPath: '/office/clients'
      preLoaderRoute: typeof OfficeClientsRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/documents': {
      id: '/office/documents'
      path: '/documents'
      fullPath: '/office/documents'
      preLoaderRoute: typeof OfficeDocumentsRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/launch': {
      id: '/office/launch'
      path: '/launch'
      fullPath: '/office/launch'
      preLoaderRoute: typeof OfficeLaunchRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/messages': {
      id: '/office/messages'
      path: '/messages'
      fullPath: '/office/messages'
      preLoaderRoute: typeof OfficeMessagesRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/offers': {
      id: '/office/offers'
      path: '/offers'
      fullPath: '/office/offers'
      preLoaderRoute: typeof OfficeOffersRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/reports': {
      id: '/office/reports'
      path: '/reports'
      fullPath: '/office/reports'
      preLoaderRoute: typeof OfficeReportsRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/requests': {
      id: '/office/requests'
      path: '/requests'
      fullPath: '/office/requests'
      preLoaderRoute: typeof OfficeRequestsRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/settings': {
      id: '/office/settings'
      path: '/settings'
      fullPath: '/office/settings'
      preLoaderRoute: typeof OfficeSettingsRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/tasks': {
      id: '/office/tasks'
      path: '/tasks'
      fullPath: '/office/tasks'
      preLoaderRoute: typeof OfficeTasksRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/account': {
      id: '/portal/account'
      path: '/account'
      fullPath: '/portal/account'
      preLoaderRoute: typeof PortalAccountRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/appointments': {
      id: '/portal/appointments'
      path: '/appointments'
      fullPath: '/portal/appointments'
      preLoaderRoute: typeof PortalAppointmentsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/requests': {
      id: '/portal/requests'
      path: '/requests'
      fullPath: '/portal/requests'
      preLoaderRoute: typeof PortalRequestsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office/clients/': {
      id: '/office/clients/'
      path: '/'
      fullPath: '/office/clients/'
      preLoaderRoute: typeof OfficeClientsIndexRouteImport
      parentRoute: typeof OfficeClientsRoute
    }
    '/office/clients/$clientId': {
      id: '/office/clients/$clientId'
      path: '/$clientId'
      fullPath: '/office/clients/$clientId'
      preLoaderRoute: typeof OfficeClientsClientIdRouteImport
      parentRoute: typeof OfficeClientsRoute
    }
    '/portal/services/$slug': {
      id: '/portal/services/$slug'
      path: '/services/$slug'
      fullPath: '/portal/services/$slug'
      preLoaderRoute: typeof PortalServicesSlugRouteImport
      parentRoute: typeof PortalRoute
    }
  }
}

interface OfficeClientsRouteChildren {
  OfficeClientsClientIdRoute: typeof OfficeClientsClientIdRoute
  OfficeClientsIndexRoute: typeof OfficeClientsIndexRoute
}

const OfficeClientsRouteChildren: OfficeClientsRouteChildren = {
  OfficeClientsClientIdRoute: OfficeClientsClientIdRoute,
  OfficeClientsIndexRoute: OfficeClientsIndexRoute,
}

const OfficeClientsRouteWithChildren = OfficeClientsRoute._addFileChildren(
  OfficeClientsRouteChildren,
)

interface OfficeRouteChildren {
  OfficeAppointmentsRoute: typeof OfficeAppointmentsRoute
  OfficeClientsRoute: typeof OfficeClientsRouteWithChildren
  OfficeDocumentsRoute: typeof OfficeDocumentsRoute
  OfficeLaunchRoute: typeof OfficeLaunchRoute
  OfficeMessagesRoute: typeof OfficeMessagesRoute
  OfficeOffersRoute: typeof OfficeOffersRoute
  OfficeReportsRoute: typeof OfficeReportsRoute
  OfficeRequestsRoute: typeof OfficeRequestsRoute
  OfficeSettingsRoute: typeof OfficeSettingsRoute
  OfficeTasksRoute: typeof OfficeTasksRoute
  OfficeIndexRoute: typeof OfficeIndexRoute
}

const OfficeRouteChildren: OfficeRouteChildren = {
  OfficeAppointmentsRoute: OfficeAppointmentsRoute,
  OfficeClientsRoute: OfficeClientsRouteWithChildren,
  OfficeDocumentsRoute: OfficeDocumentsRoute,
  OfficeLaunchRoute: OfficeLaunchRoute,
  OfficeMessagesRoute: OfficeMessagesRoute,
  OfficeOffersRoute: OfficeOffersRoute,
  OfficeReportsRoute: OfficeReportsRoute,
  OfficeRequestsRoute: OfficeRequestsRoute,
  OfficeSettingsRoute: OfficeSettingsRoute,
  OfficeTasksRoute: OfficeTasksRoute,
  OfficeIndexRoute: OfficeIndexRoute,
}

const OfficeRouteWithChildren =
  OfficeRoute._addFileChildren(OfficeRouteChildren)

interface PortalRouteChildren {
  PortalAccountRoute: typeof PortalAccountRoute
  PortalAppointmentsRoute: typeof PortalAppointmentsRoute
  PortalRequestsRoute: typeof PortalRequestsRoute
  PortalIndexRoute: typeof PortalIndexRoute
  PortalServicesSlugRoute: typeof PortalServicesSlugRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAccountRoute: PortalAccountRoute,
  PortalAppointmentsRoute: PortalAppointmentsRoute,
  PortalRequestsRoute: PortalRequestsRoute,
  PortalIndexRoute: PortalIndexRoute,
  PortalServicesSlugRoute: PortalServicesSlugRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConceptRoute: ConceptRoute,
  LoginRoute: LoginRoute,
  OfficeRoute: OfficeRouteWithChildren,
  PortalRoute: PortalRouteWithChildren,
  TermsRoute: TermsRoute,
  ApiRtcRoute: ApiRtcRoute,
  ConsultIdRoute: ConsultIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
